source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!

target 'MirrorObject_Example' do
  pod "MirrorObject", :path => "../"
end

target 'MirrorObject_Tests' do
  pod "MirrorObject", :path => "../"
end
