source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'MirrorObject_Example', :exclusive => true do
  pod "MirrorObject", :path => "../"
end

target 'MirrorObject_Tests', :exclusive => true do
  pod "MirrorObject", :path => "../"

  
end
