language: objective-c
osx_image: xcode9.4

before_install:
  - bundle install --path vender

before_script:
    #  - bundle exec pod install --project-directory=Example

script: xcodebuild -workspace Example/MirrorObject.xcworkspace -scheme MirrorObject-Example -destination 'platform=iOS Simulator,name=iPhone X,OS=11.4' test

branches:
  only:
    - master
    - develop
