language: objective-c
osx_image: xcode8

before_install:
  - gem install cocoapods -v 1.1.1 --no-document

before_script:
  - pod install --project-directory=Example

script: xcodebuild -workspace Example/MirrorObject.xcworkspace -scheme MirrorObject-Example -destination 'platform=iOS Simulator,name=iPhone 6,OS=8.4' test

branches:
  only:
    - master
    - develop
