language: objective-c
osx_image: xcode7.2

before_install:
  - gem install cocoapods -v 0.36.0 --no-document
#  - brew update
#  - brew upgrade xctool

before_script:
  - pod install --project-directory=Example

script: xcodebuild -workspace Example/MirrorObject.xcworkspace -scheme MirrorObject-Example -destination 'platform=iOS Simulator,name=iPhone 6,OS=8.4' test

branches:
  only:
    - travis
